<a href="https://colab.research.google.com/github/Natalia-Muller/Natalia-Muller/blob/main/numpy3_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center><h1> <center><h1>
<center><h1>Aprendendo Matemática com Python<center><h1>
<center><h2>Curso de Extensão</h2></center>
<center><h3>CCT - UDESC</h3></center>
<center><h2>NumPy: Vetores, Matrizes e Sistemas Lineares</h2></center>
<center><h4>Fernando Deeke Sasse e Sidnei Costa Furtado</h4></center>

## Conteúdo

- 1. Introdução
- 2. Revisão da álgebra vetorial
- 3. Normas de vetores discretos gerais
- 4. Matrizes no NumPy
- 5. Fatiamento de matrizes
- 6. Matrizes especiais
- 7. Definindo matrizes por uma lei de formação
- 8. Operações com matrizes
- 9. Normas matriciais
- 10. Número de condicionamento de uma matriz
- 11. Autovalores e autovetores de uma matriz
- 12. Sistemas Lineares
- 13. Exercícios

### 1. Introdução

Veremos neste notebook como realizar operações algébricas envolvendo vetores e matrizes.

### 2. Operações com 3-vetores espaciais

As operações mais básicas entre vetores espaciais, com aplicações em geometria analítica e mecânica são aquelas envolvendo o produto escalar e vetorial entre vetores.  Mostraremos a seguir como essas operações podem ser feitas em Numpy.

Consideremos os vetores $\mathbf{u}=(3,1,2)$ e $\mathbf{v}=(-1,2,-1)$. O produto escalar $\mathbf{u}\cdot \mathbf{v}$ pode ser feito da seguinte forma:

In [2]:
import numpy as np
u = np.array([3,1,2])
v = np.array([-1,2,-1])
np.dot(u,v)

-3

Por outro lado, o produto vetorial $\mathbf{u} \times \mathbf{v}$ é dado por

In [ ]:
np.cross(u,v)

array([-5,  1,  7])

Definiremos normas de um vetor de modo geral mais adiante. Por hora utiizaremos  a norma euclidiana de um vetor  $\mathbf{u}=(u_1,u_2, u_3)$ da forma usual,

$$
|\mathbf{u}|= \sqrt{\Sigma_{i=1}^3|u_i|^2}\,,
$$

que é simplesmente o comprimento espacial do vetor.

No Python:

In [ ]:
u = np.array([-5,1,7])
Ne = np.linalg.norm(u)
Ne

8.660254037844387

In [3]:
A = np.array([[1,2,3],[4,7,2],[3,7,8]])
np.linalg.cond(A, 1)

109.09090909090907

De fato,

In [ ]:
np.sqrt(np.sum(u**2))

8.660254037844387

Um cálculo frequentemente utilizado em dinâmica de partículas é o da projeção de um vetor na direção de outro. Sejam os vetores $\mathbf{u}=(1,4,-1)$ e $\mathbf{v}=(1,3,-5)$.

(i) Calculemos a projeção do vetor $\mathbf{u}$ na direção de $\mathbf{v}$.

Devemos calcular a expressão
$$
\mathbf{u}_{\mathbf{v}}=\left(\frac{\mathbf{u}\cdot\mathbf{v}}{|\mathbf{v}|^2}\right)\mathbf{v}
$$

No Python,

In [ ]:
u=np.array([1,4,-1])
v=np.array([1,3,-5])
uv=np.dot(u,v)/np.linalg.norm(v)**2*v
uv

array([ 0.51428571,  1.54285714, -2.57142857])

Calculemos o ângulo $\theta$ entre $\mathbf{u}$ e $\mathbf{v}$.

Para isso podemos usar a relação

$$
\mathbf{u}\cdot \mathbf{v}=|\mathbf{u}||\mathbf{v}|\cos\theta\,.
$$
Em Python,

In [ ]:
c = np.dot(u,v)/(np.linalg.norm(u)*np.linalg.norm(v))
c
theta = np.arccos(c)
theta

0.771110504762802

Em graus:

In [ ]:
theta_deg = np.degrees(theta)
theta_deg

44.18137746111112

De fato,

Um problema típico de geometria analítica consiste em calcular áreas de triângulos no espaço. Determinemos a área do triângulo com vértices $(-2,3,1)$, $(3,2,4)$ e $(2,1,8)$.

Devemos lembrar que a área do triângulo $ABC$ pode ser calculada pela fórmula

$$
A = \frac{1}{2}|\mathbf{AB}\times \mathbf{AC}|,
$$

sendo $\mathbf{AB}$ ($\mathbf{AC}$) o vetor com origem no ponto $A$ e extremidade no ponto $B$ ($C$). Façamos o cálculo em Python:

In [ ]:
A = np.array([-2,3,1])
B = np.array([3,2,4])
C = np.array([2,1,8])
AB = B-A
AC = C-A

A área é então dada por

In [ ]:
Area = np.linalg.norm(np.cross(AB,AC))/2
Area

11.895377253370318

Outro problema que podemos resolver facilmente com os comandos já explicados anteriormente consiste em determinar volumes de tetraedros.


Por exemplo, determinemos o volume do tetraedro com vértices $A =(2,3,1)$, $B = (3,-2,4)$, $C = (2,1,8)$ e $D =(-3,1,-2)$.

O volume do tetraedro é 1/6 do volume do paralepípedo definido pelos vértices acima. O volume do paralelepípedo é dado pela magnitude do produto triplo do vetores definidos pelos vértices $A$, $B$, $C$ e $D$:

$$
V_t=\frac{1}{6}|\mathbf{AB}\cdot(\mathbf{AC}\times \mathbf{AD})|
$$

Em Python temos:

In [ ]:
A = np.array([2,3,1])
B = np.array([3,-2,4])
C = np.array([2,1,8])
D = np.array([-3,1,-2])
AB = B-A
AC = C-A
AD = D-A

In [ ]:
Vt = np.linalg.norm(np.dot(AB,np.cross(AC,AD)))/6
Vt

27.5

### 3. Normas de vetores discretos gerais

Um conceito mais geral de norma vetorial geral é necessário quando tratamos de vetores em espaços de dimensões finitas superiores. As normas vetoriais são funções que atribuem a um
vetor um número real não negativo, que pode ser
interpretado como o  "tamanho"
do vetor em diferentes sentidos. Diversos teoremas em álgebra linear são formulados para normas gerais. A definição é dada a seguir.


Dado um vetor de componentes reais ou complexas $\mathbf{v} = (v_1, v_2, \dots, v_n)$, uma norma $\|\mathbf{v}\|$ deve satisfazer:


1. **Positividade:**

   $$
   \|\mathbf{v}\| \geq 0\,,
   $$
  

2. **Definitividade:**

   $$
   \|\mathbf{v}\| = 0 \quad \iff \quad \mathbf{v} = \mathbf{0}\,,
   $$
   

3. **Homogeneidade (ou linearidade em relação ao escalar):**

   $$
   \|\alpha \mathbf{v}\| = |\alpha| \|\mathbf{v}\| \quad \text{para qualquer escalar} \quad \alpha \in \mathbb{R} \text{ ou } \mathbb{C}\,,
   $$
   

4. **Desigualdade triangular:**
   $$
   \|\mathbf{u} + \mathbf{v}\| \leq \|\mathbf{u}\| + \|\mathbf{v}\|\,.
   $$
   


As normas vetoriais mais comuns são:

1. **Norma $ L_1 $** (Norma da soma absoluta):

   $$
   \| \mathbf{v} \|_1 = \sum_{i=1}^{n} |v_i|\,.
   $$

2. **Norma $ L_2 $** (Norma euclidiana):

   $$
   \| \mathbf{v} \|_2 = \sqrt{\sum_{i=1}^{n} |v_i|^2}\,.
   $$

3. **Norma $ L_\infty $** (Norma da máxima componente):

   $$
   \| \mathbf{v} \|_\infty = \max \left( |v_1|, |v_2|, \dots, |v_n| \right)\,.
   $$

Por exemplo, a norma $ L_\infty $ como critério de parada em processos iterativos, devido ao seu baixo custo computacional, principamente quando $n$ é muito grande.


Vejamos um exemplo em Python que envolve o cálculo das diferentes normas do vetor

$$
\mathbf{v} = (1,-4,2,9,-2)\,.
$$



In [ ]:
v = np.array([1,-4,2,9,-2])

In [ ]:
#Norma L1
np.linalg.norm(v,1)

18.0

In [4]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [5]:
np.linalg.norm(A,1)

18.0

In [ ]:
# Norma L2


In [ ]:
np.linalg.norm(v,2)

10.295630140987

In [6]:
np.linalg.norm(A,2)

16.84810335261421

In [ ]:
np.linalg.norm(v,np.inf)

9.0

### 4. Matrizes no NumPy

Matrizes são arrays 2-dimensionais. Por exemplo, seja a matriz $3 \times 4$:

$$
M=\begin{bmatrix}
-1& 5 & 7 & 4\\
2 & 3 & 1 & 7\\
8 & 9 & 6 & 3
\end{bmatrix}
$$

Em Python,

In [ ]:
M = np.array([[-1,5,7,4],[2,3,1,7],[8,9,6,3]])
M

array([[-1,  5,  7,  4],
       [ 2,  3,  1,  7],
       [ 8,  9,  6,  3]])

A dimensão de $M$ é dada por

In [ ]:
M.ndim

2

Sua forma é:

In [ ]:
M.shape

(3, 4)

O número total de elementos é dado por

In [ ]:
M.size

12

### 4. Fatiamento de matrizes

Podemos selecionar componentes de $M$ da forma usual. Por exemplo, o elemento da primeira linha e segunda coluna é dado por

In [ ]:
M[0,1]

5

Selecionemos a primeira coluna de $M$ para gerar um array 1D:

In [ ]:
col1 = M[:,0]
col1

array([-1,  2,  8])

Podemos forma submatrizes. Por exemplo, selecionemos a submatriz

$$
\begin{bmatrix}
 1 & 7\\
6 & 3
\end{bmatrix}
$$


In [ ]:
M[1:3,2:4]

array([[1, 7],
       [6, 3]])

### 5. Matrizes especiais

Matrizes especiais estão pré-definidas. Por exemplo

In [ ]:
I4 = np.eye(4,dtype=np.int64)
I4*1.2

array([[1.2, 0. , 0. , 0. ],
       [0. , 1.2, 0. , 0. ],
       [0. , 0. , 1.2, 0. ],
       [0. , 0. , 0. , 1.2]])

In [ ]:
B4 = np.ones((4,4))
B4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
Z3 = np.zeros((3,3))
Z3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Matrizes diagonais podem ser definidas da seguinte forma:

In [ ]:
A_diag = np.diag([1,2,3,4])
A_diag

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
np.diag(A_diag)

array([1, 2, 3, 4])

Uma matriz tridiagonal pode ser definida da seguinte forma:

In [ ]:
# Definir as diagonais
diagonal_principal = np.array([1, 2, 3, 4])
diagonal_superior = np.array([5, 6, 7])
diagonal_inferior = np.array([8, 9,3])

# Cria matrizes diagonais
matriz_principal = np.diag(diagonal_principal)
matriz_superior = np.diag(diagonal_superior, k=1)
matriz_inferior = np.diag(diagonal_inferior, k=-1)

matriz_tridiagonal = matriz_principal + matriz_superior + matriz_inferior
matriz_tridiagonal

array([[1, 5, 0, 0],
       [8, 2, 6, 0],
       [0, 9, 3, 7],
       [0, 0, 3, 4]])

Podemos definir matrizes com componentes aleatórias com diferentes distribuições:

In [ ]:
# Distribuição uniforme
np.random.seed(22)
m = 3
n = 4
np.random.rand(m,n)

array([[0.20846054, 0.48168106, 0.42053804, 0.859182  ],
       [0.17116155, 0.33886396, 0.27053283, 0.69104135],
       [0.22040452, 0.81195092, 0.01052687, 0.5612037 ]])

In [ ]:
# Distribuição normal padrão
A_normal = np.random.randn(m,n)
A_normal

array([[ 0.58775221,  0.75231758, -1.05850255,  1.05597241],
       [ 0.74775027,  1.06467659,  1.52012959, -1.48860294],
       [ 1.85998989, -1.59861303, -0.64607361,  0.337325  ]])

In [ ]:
# Distribuição normal qualquer
mean = 10
std = 2
np.random.normal(mean, std, (m,n))

array([[10.20395785,  9.49814093,  9.84237539,  7.82967167],
       [11.1898569 ,  8.72218386,  7.78432628, 14.21229151],
       [ 8.86522446,  9.04010041,  6.15354029, 10.79917708]])

Podemos definir matrizes com componentes aleatórias inteiras:

In [ ]:
A_int = np.random.randint(0,10,(m,n))
A_int

array([[0, 8, 4, 0],
       [1, 5, 6, 8],
       [2, 6, 5, 6]])

### 6. Definindo matrizes por uma lei de formação

Podemos definir uma matriz de acordo com uma lei de formação para seus elementos $a_{ij}$. O modo mais imediato, mas não eficiente,  é o seguinte:

In [ ]:
n = 4
M = np.zeros((n,n),dtype=float)
for i in range(n):
    for j in range(n):
        M[i,j] = 1/(i+j+1)+j
M

array([[1.        , 1.5       , 2.33333333, 3.25      ],
       [0.5       , 1.33333333, 2.25      , 3.2       ],
       [0.33333333, 1.25      , 2.2       , 3.16666667],
       [0.25      , 1.2       , 2.16666667, 3.14285714]])

Podemos usar o comando `fromfunction` do Numpy:

In [ ]:
n = 4
A = np.fromfunction(lambda i, j: 1/(i+j+1)+j, (n, n), dtype=float)
A

array([[1.        , 1.5       , 2.33333333, 3.25      ],
       [0.5       , 1.33333333, 2.25      , 3.2       ],
       [0.33333333, 1.25      , 2.2       , 3.16666667],
       [0.25      , 1.2       , 2.16666667, 3.14285714]])

Outro modo de definir uma matriz é a seguinte:

In [ ]:
A = np.array([[1/(i+j+1)+j for j in range(n)] for i in range(n)])
A

array([[1.        , 1.5       , 2.33333333, 3.25      ],
       [0.5       , 1.33333333, 2.25      , 3.2       ],
       [0.33333333, 1.25      , 2.2       , 3.16666667],
       [0.25      , 1.2       , 2.16666667, 3.14285714]])

### 7. Operações com matrizes

Seja a matrix  $M$ dada por:  

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

Operações sobre arrays são feitas elemento a elemento. Por exemplo.

In [ ]:
#Eleva cada componente ao quadrado
A**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [ ]:
#Calcula o seno de cada componente
np.sin(A)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

Para elevar a matriz quadrado fazemos

In [ ]:
A@A

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
np.transpose(A)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

A matriz tranposta de $A$ é dada por

In [ ]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Notemos, como esperado, que $A A^T$ é simétrica:

In [ ]:
A@A.T

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

Façamos uma multiplicação matricial usual entre uma matriz e um vetor.
Consideremos a seguinte matriz $ A $ e o vetor $ \mathbf{v} $:

$$
A = \begin{bmatrix}
2 & 3 & -1 \\
0 & 1 & 4 \\
-2 & 0 & 5
\end{bmatrix}
$$

$$
\mathbf{v} = \begin{bmatrix}
1 \\
-1 \\
2
\end{bmatrix}
$$

Queremos calcular o produto $ A\mathbf{v} $. Isso pode ser feito de dois modos:

(i) Definimos uma matriz $1 \times 3$(note os dois colchetes, que caracteriza o 2-array):

In [ ]:
A = np.array([[2,3,-1],[0,1,4],[-2,0,5]])
v = np.array([1,-1,2])
A@v

array([-3,  7,  8])

In [ ]:
np.dot(A,v)

array([-3,  7,  8])

In [ ]:
u = np.array([[1,2,3]])
u

array([[1, 2, 3]])

In [ ]:
ut = u.T
ut

array([[1],
       [2],
       [3]])

In [ ]:
A@u.T

array([[ 5],
       [14],
       [13]])

In [ ]:
u.shape

(1, 3)

In [ ]:
v.shape

(3,)

Para calcular a inversa de uma matriz procedemos do seguinte modo:

In [ ]:
np.linalg.inv(A)

array([[-0.3125,  0.9375, -0.8125],
       [ 0.5   , -0.5   ,  0.5   ],
       [-0.125 ,  0.375 , -0.125 ]])

In [ ]:
A = np.array([[1,2,3], [4,3,2], [3,6,7]])
A

array([[1, 2, 3],
       [4, 3, 2],
       [3, 6, 7]])

O traço da matriz $A$ (soma dos elementos da diagonal) é dado por

In [ ]:
np.trace(A)

11

O determinante é dado por:

In [ ]:
np.linalg.det(A)

10.000000000000002

Suponhamos que $A$ é uma matrix de componentes complexas:

In [ ]:
Ac = np.array([[1+2j, 3+4j], [5+6j, 7+8j]])
Ac

array([[1.+2.j, 3.+4.j],
       [5.+6.j, 7.+8.j]])

A matrix transposta  conjugada(ou hermitiana conjugada) de $A$, denominada $A^{\dagger}$ é dada por

In [ ]:
AH = np.conjugate(Ac.T)
AH

array([[1.-2.j, 5.-6.j],
       [3.-4.j, 7.-8.j]])

Notemos que

 Se a $A^{\dagger}=A$, a matriz é dita hermitiana. Se $A^{\dagger}A=AA^{\dagger}=I$, ou $A^{\dagger}=A^{-1}$, a matriz é dita unitária. Nesse caso, a matriz hermiana conjugada é igual à sua inversa. Tais matrizes são fundamentais em mecânica quântica, pois matrizes hermitianas têm autovalores reais (observáveis físicos) e uma matriz unitária preserva a norma $\mathbf{v}^{\dagger}\mathbf{v}$ de um vetor $\mathbf{v}$:

$$
(U\mathbf{v})^{\dagger}U\mathbf{v} = \mathbf{v}^{\dagger}U^{\dagger}U\mathbf{v} = \mathbf{v}^{\dagger}\mathbf{v}\,.
$$


### 8. Normas matriciais

Normas matriciais são funções que atribuem um número real não negativo a uma matriz, quantificando o "tamanho" ou "magnitude" da matriz de uma maneira específica. Assim como as normas vetoriais medem o comprimento ou a magnitude de um vetor, as normas matriciais são usadas para medir determinados tipos de magnitude de uma matriz.

As normas matriciais são amplamente utilizadas em álgebra linear, análise numérica e outras áreas matemáticas para analisar a estabilidade, sensibilidade e comportamento de operações envolvendo matrizes.

Uma função $ \|\cdot\|: \mathbb{R}^{m \times n} \rightarrow \mathbb{R} $ é considerada uma norma matricial se satisfizer as seguintes condições:

1. Subaditividade (Desigualdade Triangular):
   $$
   \|A + B\| \leq \|A\| + \|B\| \quad \text{para todas as matrizes } A \text{ e } B \text{ de mesma dimensão}.
   $$


2. Multiplicação Escalar:
   $$
   \|\alpha A\| = |\alpha| \cdot \|A\| \quad \text{para todo escalar } \alpha \text{ e matriz } A.
   $$


3. Não-Negatividade e Definitividade:
  $$
   \|A\| \geq 0 \quad \text{e} \quad \|A\| = 0 \text{ se e somente se } A = 0.
   $$
   
   
4. Compatibilidade com a Multiplicação Matricial:
   $$
   \|AB\| \leq \|A\| \cdot \|B\| \quad \text{para todas as matrizes } A \text{ e } B \text{ onde o produto } AB \text{ é definido}.
   $$



Examinemos os principais tipos de normas matriciais:

- Norma 1 (Norma da Coluna Máxima, $ p = 1 $):
  $$
  \|A\|_1 = \max_{1 \leq j \leq n} \sum_{i=1}^{m} |a_{ij}|
  $$
  A norma 1 mede a maior soma absoluta das colunas da matriz.
  
  Em Python,

In [ ]:
import numpy as np
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
# Norma 1
norm1 = np.linalg.norm(A, 1)
norm1

18.0

- Norma 2 (Norma Espectral, $ p = 2 $):
  $$
  \|A\|_2 = \sqrt{\lambda_{\text{max}}}\,,
  $$
  sendo  $ \lambda_{\text{max}}$ maior autovalor de $ A^{\dagger}A $. Aqui $A^{\dagger}$ é a matriz hermitiana conjugada de $A$. Se $A$ for real, $A^{\dagger}=A^T$ Em Python,

In [ ]:
norm2 = np.linalg.norm(A, 2)
norm2

16.84810335261421

- Norma Infinito (Norma da Linha Máxima, $ p = \infty $):
  $$
  \|A\|_\infty = \max_{1 \leq i \leq m} \sum_{j=1}^{n} |a_{ij}|
  $$
  
  A norma infinito mede a maior soma absoluta das linhas da matriz. Em Python,

In [ ]:
norm_inf = np.linalg.norm(A, np.inf)
norm_inf

24.0

- Norma de Frobenius:

$$
\|A\|_F = \sqrt{\sum_{i=1}^{m} \sum_{j=1}^{n} |a_{ij}|^2}
$$

Esta norma é equivalente à norma 2 para o vetor de elementos da matriz, sendo a raiz quadrada da soma dos quadrados de todos os elementos da matriz. Em Python,

In [ ]:
np.linalg.norm(A,'fro')

16.881943016134134

Normas matriciais podem ser usadas para estabelecer critérios de parada em algoritmos numéricos, análise de estabilidade de equações diferenciais, etc. Uma aplicação que exemplificaremos aqui é o cálculo do número de condionamento de uma matriz.

### 9. Número de condicionamento de uma matriz

O número de condicionamento de uma matriz $ A $ é definido como:

$$
\kappa(A) = \|A\| \cdot \|A^{-1}\|\,,
$$

sendo $ \|A\| $ a norma da matriz $ A$, e $ \|A^{-1}\| $ é a norma de sua inversa.  

Esta é uma medida que indica a sensibilidade da solução de um sistema linear em relação a mudanças nos dados de entrada. Um número de condicionamento elevado sugere que a matriz pode causar problemas numéricos, como soluções instáveis ou imprecisas.

O número de condicionamento frequentemente utiliza a norma 2 (norma espectral), que está relacionada aos autovalores da matriz. Este é o default em Python:

In [ ]:
A = np.array([[1,2,3],[4,7,2],[3,7,8]])

Usando outras normas:

In [ ]:
# Condição de A, norma 1
np.linalg.cond(A,1)

109.09090909090907

In [ ]:
# Condição de A com norma infinito
np.linalg.cond(A,np.inf)

104.72727272727272

In [ ]:
# Norma Frobenius
np.linalg.cond(A,'fro')

70.16686133604712

In [ ]:
B = np.array([[1,-1],[-1000,999]])
C = np.array([0,1000])
np.linalg.solve(B,C)

array([-1000., -1000.])

In [ ]:
B = np.array([[1,-1],[-1001,999]])
C = np.array([0,1000])
np.linalg.solve(B,C)

array([-500., -500.])

In [ ]:
np.linalg.cond(B,1)

1001999.9999999783

### 10. Autovalores e autovetores de uma matriz

Consideremos o problema de determinar os autovalores e autovetores da seguinte matriz

$$
A = \begin{bmatrix}
2 & -1 & 0 \\
1 & 3 & -1 \\
0 & 2 & 1 \\
\end{bmatrix}
$$

Os autovalores $ \lambda $ são determinados pela equação característica:

$$
\det(A - \lambda I) = 0
$$

ou seja,

$$
\det(A - \lambda I) = \left| \begin{array}{ccc}
2 - \lambda & -1 & 0 \\
1 & 3 - \lambda & -1 \\
0 & 2 & 1 - \lambda \\
\end{array} \right|=\lambda^3 - 6\lambda^2 + 14\lambda - 11 = 0\,.
$$

Utilizaremos o Python para encontrar as raízes da equação:

In [ ]:
import numpy as np

In [ ]:
# Coeficientes do polinômio característico


# Encontrar as raízes da equação cúbica


Autovalores:
[2.22669883+1.46771151j 2.22669883-1.46771151j 1.54660235+0.j        ]


Podemos utilizar o Python para calcular os autovalores e autovetores diretamente:

array([2.22669883+1.46771151j, 2.22669883-1.46771151j,
       1.54660235+0.j        ])

array([[ 0.36126918-0.21800183j,  0.36126918+0.21800183j,
        -0.50266229+0.j        ],
       [-0.4018631 -0.48081818j, -0.4018631 +0.48081818j,
        -0.2279059 +0.j        ],
       [-0.6551944 +0.j        , -0.6551944 -0.j        ,
        -0.83390019+0.j        ]])

Verifiquemos os resultados. Por exemplo, examinemos se para o primeiro autovalor $\lambda_1 $ e autovetor $\mathbf{v}_1$ acima temos $A\mathbf{v}_1=\lambda_1 \mathbf{v}_1$:

array([ 6.66133815e-16+9.99200722e-16j, -9.99200722e-16+0.00000000e+00j,
       -2.22044605e-16-7.77156117e-16j])

Equivalentemente tal verificação poderia ser feita do seguinte modo:

True

### 11. Sistemas Lineares

Definiremos funções em Python que realizam as operações elementares sobre linhas de uma matriz que serão úteis para resolver sistemas de equações lineares ou simplesmente, sistemas lineares.  Um [sistema linear](https://pt.wikipedia.org/wiki/Sistema_de_equações_lineares) é um conjunto de equações lineares acopladas entre por meio de variáveis $x_1,\ldots, x_n$, da forma:

$$
\left\{
\begin{aligned}
a_{11}x_1 + a_{12}x_2 + \cdots + a_{1n}x_n & = b_1 \\
a_{10}x_1 + a_{22}x_2 + \cdots + a_{2n}x_n & = b_2 \\
& \vdots \\
a_{m1}x_1 + a_{m1}x_2 + \cdots + a_{mn}x_n & = b_m \\
\end{aligned}
\right.
$$

Em notação matricial o sistema linear de $n$ equações  e $n$ incógnitas é representado na forma
 $A X= B$, sendo

$$
A = \begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & & & \vdots \\\
a_{n 1} & a_{n 2} & \cdots & a_{n n} \\
\end{bmatrix}
 \ \ , \ \
X = \begin{bmatrix}
x_1 \\\ x_2 \\ \vdots \\ x_n
\end{bmatrix}
 \ \ , \ \
b= \begin{bmatrix}
b_1 \\\ b_2 \\\ \vdots \\ b_n
\end{bmatrix}
$$

**Exemplo.** Consideremos o seguinte sistema de equações lineares:

$$
\begin{cases}
2x + 3y - z = 5 \\
4x + y + 2z = 6 \\
-2x + 5y + 2z = -1\,.
\end{cases}
$$

Nosso objetivo é encontrar os valores de $ x $, $ y $ e $ z $ que satisfaçam simultaneamente todas as três equações.

Utilizaremos a biblioteca NumPy do Python para resolver o sistema.  Na forma matricial reescrevemos o sistema como:

$$
\begin{bmatrix}
2 & 3 & -1 \\
4 & 1 & 2 \\
-2 & 5 & 2
\end{bmatrix}
\begin{bmatrix}
x \\ y \\ z
\end{bmatrix}
=
\begin{bmatrix}
5 \\ 6 \\ -1
\end{bmatrix}\,,
$$

com:

$$
A = \begin{bmatrix} 2 & 3 & -1 \\ 4 & 1 & 2 \\ -2 & 5 & 2 \end{bmatrix}, \quad
X = \begin{bmatrix} x \\ y \\ z \end{bmatrix}, \quad
b = \begin{bmatrix} 5 \\ 6 \\ -1 \end{bmatrix}\,.
$$

Resolvamos este problema em Python,  usando comandos do Numpy:

In [ ]:
import numpy as np

array([ 1.52702703,  0.54054054, -0.32432432])

Podemos verificar o resultado:

array([ 0.0000000e+00,  0.0000000e+00, -4.4408921e-16])

### 12. Exercícios

**1.** Dados os vetores

$$
\mathbf{v}_1=(4,5,3)\,,\quad \mathbf{v}_2=(5,2,6)\,,
$$

(i) Determine o ângulo entre os dois vetores.

(ii) Determine o vetor projeção de $\mathbf{v}_1$ na direção de $\mathbf{v}_2$.

**2.** Determine a área do triângulo de vértices $(3,4,2)$, $(-2,1,9)$ e $(-4,2,-1)$.

**3.** Dados os vetores

$$
\mathbf{v}_1=(2,5,1)\,,\qquad \mathbf{v}_2=(-1,2,-3)\,,\quad \mathbf{v}_3=(-4,1,-7)\,,
$$

determine o volume do paralelepípedo definido por esses vetores.

**4.** Verifique  que a norma de Frobenius da matriz

$$
M=\begin{bmatrix}
-3 & 7 & 3 \\
2 & -5 & 4 \\
1 & 9 & -1
\end{bmatrix}
$$

pode também ser dada por

$$
||\mathbf{M}||_F=\sqrt{\left(\mbox{Tr}(M M^T\right)}\,.
$$

**5.** Sejam as matrizes
$$ A =
\begin{bmatrix}
1 & -2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}\,,\qquad
B =
\begin{bmatrix}
9 & 4 & 6 \\
6 & 3 & 2 \\
1 & 2 & 3
\end{bmatrix}\,.
$$

(i) Determine $C=A^3-AB -4I$, sendo $I$ a matriz identidade $3 \times 3$.

(ii) Use a equação  $det(C-I\lambda)=0$ para encontrar os autovalores de $C$.

**6.** Seja o sistema linear

$$
\begin{bmatrix}
-1 & -2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
\begin{bmatrix}
x  \\
y  \\
z
\end{bmatrix}
=
\begin{bmatrix}
1  \\
4  \\
3\,.
\end{bmatrix}
$$

Resolva o sistema calculando explicitamente  a expressão:

$$
\begin{bmatrix}
x  \\
y  \\
z
\end{bmatrix}= \begin{bmatrix}
-1 & -2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}^{-1}\begin{bmatrix}
1  \\
4  \\
3\,.
\end{bmatrix}
$$

Note que este não é o método mais eficiente para resolver um sistema linear.

**7.** Determine as normas $\|\mathbf{v}\|_1$, $\|\mathbf{v}\|_2$ e $
\|\mathbf{v}\|_{\infty}$ do vetor

$$
\mathbf{v}=( 1+2i,3-5i,2+i,2-5i,4-3i)\,.
$$

**7.** Determine os autovalores e autovetores da matriz

$$
A = \begin{bmatrix}
4 & 1 & 2 & 0 \\
1 & 3 & 0 & 1 \\
2 & 0 & 2 & 3 \\
0 & 1 & 3 & 4 \\
\end{bmatrix}\,.
$$

**8.** Mostre que a matriz

$$
U = \frac{1}{2} \begin{bmatrix}
1 & i & 1 & i \\
i & 1 & -i & 1 \\
1 & -i & 1 & -i \\
i & 1 & -i & 1
\end{bmatrix}
$$

é unitária e verifique a  norma  $\|\mathbf{v}\|^2 = \mathbf{v}^{\dagger}\mathbf{v}$ do vetor

$$
\mathbf{v} = \begin{bmatrix}
1 + i \\
2 - 6i \\
3 + 2i \\
4 - 5i
\end{bmatrix}
$$

é preservada após a operação $U \mathbf{v}$.


**9**. Calcule os autovalores e autovetores da matriz

$$
H = \begin{bmatrix}
2 & 1 + i & 4 - 2i \\
1 - i & 3 & 5 + i \\
4 + 2i & 5 - i & 1\,.
\end{bmatrix}
$$

Por que é esperado que os autovalores sejam reais?

**10.** As matrizes de Hilbert têm a seguinte lei de formação $a_{ij}=1/(i+j-1)$ para $i=1,\cdots,n$. Tais matrizes são muito usadas em testes de algoritmos numéricos, pelo fato de serem mal condicionadas. Construa uma função que calcula o número de condição (usando qualquer tipo de norma) de matrizes de Hilbert de ordem $3\times 3, 4\times 4, \ldots, 40\times 40$. Faça o mesmo para uma matriz de componentes aleatórias. Faça um gráfico simultâneo comparando a variação do número de condição para as duas matrizes.

**11.** Resolva o sistema linear dado por

$$
\left\{
\begin{aligned}
2x_1 + 3x_2 - x_3 + 4x_4 + x_5 & = 7 \\
-3x_1 + 5x_2 + 2x_3 - 6x_4 + 8x_5 & = -2 \\
4x_1 - x_2 + 7x_3 + 3x_4 - 5x_5 & = 10 \\
x_1 + 6x_2 - 3x_3 + 2x_4 + 4x_5 & = 5 \\
-2x_1 + 4x_2 + 5x_3 - x_4 + 6x_5 & = 1 \\
\end{aligned}
\right.
$$

e verifique o resultado.