<a href="https://colab.research.google.com/github/Natalia-Muller/Natalia-Muller/blob/main/Tarefa_1_anu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 <center>  <font size=5> <strong>Tarefa 1 de Análise Numérica</strong> </font>

Eliminação Gaussiana Simples

Natália Muller
</center>


Vamos considerar o sistema linear $AX=B$, com

$$
A = \begin{bmatrix}
0 & 2 & 3& 5 \\
4 & -5 & 6& -3 \\
1 & 5 & 2 & 1\\
2 & -4 & 1 & 3
\end{bmatrix}\,,
\qquad
B =
\begin{bmatrix}
1  \\
-4  \\
2\\
3
\end{bmatrix}\,.
$$


**(i)** Vamos, primeiramente, achar a forma echelon da matriz expandida, passo a passo, ou seja, definindo todas as operações a serem feitas.

M será nossa matriz expandida:

In [37]:
import numpy as np
A = np.array([[0,2,3,5],[4,-5,6,-3],[1,5,2,1],[2,-4,1,3]])
B = np.array([[1],[-4],[2],[3]])
M = np.array([[0,2,3,5,1],[4,-5,6,-3,-4],[1,5,2,1,2],[2,-4,1,3,3]])
M

array([[ 0,  2,  3,  5,  1],
       [ 4, -5,  6, -3, -4],
       [ 1,  5,  2,  1,  2],
       [ 2, -4,  1,  3,  3]])

Podemos trocar a primeira linha com a segunda, já que temos um zero como primeiro elemento.

In [8]:
E1 = ([[0,1,0,0],[1,0,0,0],[0,0,1,0],[0,0,0,1]])
M1 = E1@M
M1

array([[ 4, -5,  6, -3, -4],
       [ 0,  2,  3,  5,  1],
       [ 1,  5,  2,  1,  2],
       [ 2, -4,  1,  3,  3]])

Agora vamos multiplicar a primeira linha por -1/4 e somar com a terceira linha

In [9]:
E2 = ([[1,0,0,0],[0,1,0,0],[-1/4,0,1,0],[0,0,0,1]])
M2 = E2@M1
M2

array([[ 4.  , -5.  ,  6.  , -3.  , -4.  ],
       [ 0.  ,  2.  ,  3.  ,  5.  ,  1.  ],
       [ 0.  ,  6.25,  0.5 ,  1.75,  3.  ],
       [ 2.  , -4.  ,  1.  ,  3.  ,  3.  ]])

Multiplicar a segunda linha por -6.25/2 e somar com a terceira linha

In [12]:
E3 = ([[1,0,0,0],[0,1,0,0],[0,-6.25/2,1,0],[0,0,0,1]])
M3 = E3@M2
M3

array([[  4.   ,  -5.   ,   6.   ,  -3.   ,  -4.   ],
       [  0.   ,   2.   ,   3.   ,   5.   ,   1.   ],
       [  0.   ,   0.   ,  -8.875, -13.875,  -0.125],
       [  2.   ,  -4.   ,   1.   ,   3.   ,   3.   ]])

Multiplicar a primeira linha por -2/4 e somar à quarta linha

In [13]:
E4 = ([[1,0,0,0],[0,1,0,0],[0,0,1,0],[-2/4,0,0,1]])
M4 = E4@M3
M4

array([[  4.   ,  -5.   ,   6.   ,  -3.   ,  -4.   ],
       [  0.   ,   2.   ,   3.   ,   5.   ,   1.   ],
       [  0.   ,   0.   ,  -8.875, -13.875,  -0.125],
       [  0.   ,  -1.5  ,  -2.   ,   4.5  ,   5.   ]])

Multiplicar a segunda linha por 1.5/2 e somar à quarta linha

In [14]:
E5 = ([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,1.5/2,0,1]])
M5 = E5@M4
M5

array([[  4.   ,  -5.   ,   6.   ,  -3.   ,  -4.   ],
       [  0.   ,   2.   ,   3.   ,   5.   ,   1.   ],
       [  0.   ,   0.   ,  -8.875, -13.875,  -0.125],
       [  0.   ,   0.   ,   0.25 ,   8.25 ,   5.75 ]])

Multiplicar a terceira linha por 0.25/8.875 e somar à quarta linha

In [16]:
E6 = ([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0.25/8.875,1]])
M6 = E6@M5
M6

array([[  4.        ,  -5.        ,   6.        ,  -3.        ,
         -4.        ],
       [  0.        ,   2.        ,   3.        ,   5.        ,
          1.        ],
       [  0.        ,   0.        ,  -8.875     , -13.875     ,
         -0.125     ],
       [  0.        ,   0.        ,   0.        ,   7.85915493,
          5.74647887]])

Temos que M6 é a forma echelon da matriz aumentada.

**(ii)** Faremos as mesmas operações, porém agora com funções pré-definidas

In [17]:
M

array([[ 0,  2,  3,  5,  1],
       [ 4, -5,  6, -3, -4],
       [ 1,  5,  2,  1,  2],
       [ 2, -4,  1,  3,  3]])

A função sum_rows soma a linha j multiplicada k vezes com a linha i. E se i=i, teremos $E_{ii}=k+1$.

In [18]:
def sum_rows(A,k,i,j):
    "Add k times row j to row i"
    n=A.shape[0]
    E=np.eye(n)
    if i == j:
        E[i,i] = k+1
    else:
        E[i,j] = k
    return E@A

A função swap_rows troca as linhas i e j de lugar

In [21]:
def swap_rows(A,i,j):
    "Swap rows i and j"
    n=A.shape[0]
    E=np.eye(n)
    E[i,i]=0
    E[j,j]=0
    E[i,j]=1
    E[j,i]=1
    return E@A

In [22]:
M1 = swap_rows(M,0,1)
M1

array([[ 4., -5.,  6., -3., -4.],
       [ 0.,  2.,  3.,  5.,  1.],
       [ 1.,  5.,  2.,  1.,  2.],
       [ 2., -4.,  1.,  3.,  3.]])

In [23]:
M2 = sum_rows(M1,-1/4,2,0)
M2

array([[ 4.  , -5.  ,  6.  , -3.  , -4.  ],
       [ 0.  ,  2.  ,  3.  ,  5.  ,  1.  ],
       [ 0.  ,  6.25,  0.5 ,  1.75,  3.  ],
       [ 2.  , -4.  ,  1.  ,  3.  ,  3.  ]])

In [24]:
M3 = sum_rows(M2,-6.25/2,2,1)
M3

array([[  4.   ,  -5.   ,   6.   ,  -3.   ,  -4.   ],
       [  0.   ,   2.   ,   3.   ,   5.   ,   1.   ],
       [  0.   ,   0.   ,  -8.875, -13.875,  -0.125],
       [  2.   ,  -4.   ,   1.   ,   3.   ,   3.   ]])

In [25]:
M4 = sum_rows(M3,-2/4,3,0)
M4

array([[  4.   ,  -5.   ,   6.   ,  -3.   ,  -4.   ],
       [  0.   ,   2.   ,   3.   ,   5.   ,   1.   ],
       [  0.   ,   0.   ,  -8.875, -13.875,  -0.125],
       [  0.   ,  -1.5  ,  -2.   ,   4.5  ,   5.   ]])

In [27]:
M5 = sum_rows(M4,1.5/2,3,1)
M5

array([[  4.   ,  -5.   ,   6.   ,  -3.   ,  -4.   ],
       [  0.   ,   2.   ,   3.   ,   5.   ,   1.   ],
       [  0.   ,   0.   ,  -8.875, -13.875,  -0.125],
       [  0.   ,   0.   ,   0.25 ,   8.25 ,   5.75 ]])

In [28]:
M6 = sum_rows(M5,0.25/8.875,3,2)
M6

array([[  4.        ,  -5.        ,   6.        ,  -3.        ,
         -4.        ],
       [  0.        ,   2.        ,   3.        ,   5.        ,
          1.        ],
       [  0.        ,   0.        ,  -8.875     , -13.875     ,
         -0.125     ],
       [  0.        ,   0.        ,   0.        ,   7.85915493,
          5.74647887]])

**(III)** Podemos, neste momento, fazer as substituições e encontrar as soluções deste sistema

In [29]:
x3 = M6[3,4]/M6[3,3]
x3

0.7311827956989247

In [44]:
x2 = (M6[2,4] - x3*M6[2,3])/M6[2,2]
x2

-1.129032258064516

In [45]:
x1 = (M6[1,4] - x3*M6[1,3] - x2*M6[1,2])/M6[1,1]
x1

0.36559139784946204

In [46]:
x0 = (M6[0,4] - x1*M6[0,1] - x2*M6[0,2] - x3*M6[0,3])/M6[0,0]
x0

1.698924731182795

Portanto a solução é dada por

In [47]:
x = np.transpose(np.array([[x0,x1,x2,x3]]))
x

array([[ 1.69892473],
       [ 0.3655914 ],
       [-1.12903226],
       [ 0.7311828 ]])

Calculando o resíduo:

In [48]:
A@x-B

array([[ 0.00000000e+00],
       [ 0.00000000e+00],
       [-1.77635684e-15],
       [ 0.00000000e+00]])

**(IV)** Por último, podemos obter a solução usando um solucionador do numpy. Aqui podemos verificar que os cálculos foram efetuados corretamente. Por mais que um resíduo ínfimo tenha surgido.

In [49]:
x = np.linalg.solve(A,B)
print(x)

[[ 1.69892473]
 [ 0.3655914 ]
 [-1.12903226]
 [ 0.7311828 ]]
